### ISSUE TITLE
Marlin mks 1.4 archlinux

### ISSUE THREAD

**Issue by dudman** [cncjs/cncjs#400]
#### Description
Board works on octopi, I can move/control stepper. However connect it to cncjs and I can't move the stepper motor. The Marlin consol connects. And I get the following output...

Cap:PROGRESS:0
Cap:PRINT_JOB:1
Cap:AUTOLEVEL:0
Cap:Z_PROBE:0
Cap:LEVELING_DATA:0
Cap:BUILD_PERCENT:0
Cap:SOFTWARE_POWER:0
Cap:TOGGLE_LIGHTS:0
Cap:CASE_LIGHT_BRIGHTNESS:0
Cap:EMERGENCY_PARSER:0
Cap:AUTOREPORT_SD_STATUS:0
Cap:TROTECTION:1
ok
00.00 Y:0.00 Z:0.00 E:0.00 Count X:0 Y:0 Z:0

this is the output from command line 
sudo cncjs -p 82 -vvv --controller Marlin

2018-12-29T14:33:22.690Z - silly: controller:Marlin < Cap:SERIAL_XON_XOFF:0
2018-12-29T14:33:22.690Z - silly: controller:Marlin < Cap:EEPROM:0
2018-12-29T14:33:22.690Z - silly: controller:Marlin < Cap:VOLUMETRIC:1
2018-12-29T14:33:22.691Z - silly: controller:Marlin < Cap:AUTOREPORT_TEMP:1
2018-12-29T14:33:22.691Z - silly: controller:Marlin < Cap:PROGRESS:0
2018-12-29T14:33:22.691Z - silly: controller:Marlin < Cap:PRINT_JOB:1
2018-12-29T14:33:22.691Z - silly: controller:Marlin < Cap:AUTOLEVEL:0
2018-12-29T14:33:22.691Z - silly: controller:Marlin < Cap:Z_PROBE:0
2018-12-29T14:33:22.691Z - silly: controller:Marlin < Cap:LEVELING_DATA:0
2018-12-29T14:33:22.691Z - silly: controller:Marlin < Cap:BUILD_PERCENT:0
2018-12-29T14:33:22.691Z - silly: controller:Marlin < Cap:SOFTWARE_POWER:0
2018-12-29T14:33:22.692Z - silly: controller:Marlin < Cap:TOGGLE_LIGHTS:0
2018-12-29T14:33:22.692Z - silly: controller:Marlin < Cap:CASE_LIGHT_BRIGHTNESS:0
2018-12-29T14:33:22.692Z - silly: controller:Marlin < Cap:EMERGENCY_PARSER:0
2018-12-29T14:33:22.692Z - silly: controller:Marlin < Cap:AUTOREPORT_SD_STATUS:0
2018-12-29T14:33:22.702Z - silly: controller:Marlin < Cap:T_PROTECTION:1
2018-12-29T14:33:22.702Z - silly: controller:Marlin < ok
2018-12-29T14:33:22.703Z - silly: controller:Marlin controller.on('ok'): source=feeder, line="M115", res={"raw":"ok"}
2018-12-29T14:33:22.893Z - silly: controller:Marlin < 00.00 Y:0.00 Z:0.00 E:0.00 Count X:0 Y:0 Z:0
2018-12-29T14:33:22.894Z - silly: controller:Marlin < ok
2018-12-29T14:33:22.894Z - silly: controller:Marlin controller.on('ok'): source=server, line="M114", res={"raw":"ok"}
2018-12-29T14:33:23.404Z - silly: controller:Marlin < 100.00 Y:0.00 Z:0.00 E:0.00 Cont X:0 Y:0 Z:0
2018-12-29T14:33:23.405Z - silly: controller:Marlin < ok
2018-12-29T14:33:23.405Z - silly: controller:Marlin controller.on('ok'): source=server, line="M114", res={"raw":"ok"}
2018-12-29T14:33:23.898Z - silly: controller:Marlin <  T:-15.00 /0.00 @:0
2018-12-29T14:33:23.899Z - silly: controller:Marlin controller.on('temperature'): source=server, line="M105", res={"ok":false,"extruder":{"deg":"-15.00","degTarget":"0.00","power":"0"},"heatedBed":{},"raw":" T:-15.00 /0.00 @:0"}
2018-12-29T14:33:26.913Z - silly: controller:Marlin < -15.00 /0.00 @:0
2018-12-29T14:33:29.392Z - silly: controller:Marlin Reschedule current position query: now=1546094009392ms, timespan=5009ms
2018-12-29T14:33:29.931Z - silly: controller:Marlin < ok T:-15.00 /0.00 @:0
2018-12-29T14:33:29.931Z - silly: controller:Marlin controller.on('temperature'): source=server, line="M105", res={"ok":true,"extruder":{"deg":"-15.00","degTarget":"0.00","power":"0"},"heatedBed":{},"raw":"ok T:-15.00 /0.00 @:0"}
2018-12-29T14:33:29.931Z - silly: controller:Marlin controller.on('ok'): source=server, line="M105", res=undefined
2018-12-29T14:33:30.559Z - debug: service:cncengine socket.command("/dev/ttyUSB2", "gcode"): id=5OGKtp6cqWNiSue0AAAA     at Socket.<anonymous> (/usr/lib/cncjs/app/index.js:16937:21)
2018-12-29T14:33:30.560Z - debug: service:cncengine socket.command("/dev/ttyUSB2", "gcode"): id=5OGKtp6cqWNiSue0AAAA     at Socket.<anonymous> (/usr/lib/cncjs/app/index.js:16937:21)
2018-12-29T14:33:30.560Z - debug: service:cncengine socket.command("/dev/ttyUSB2", "gcode"): id=5OGKtp6cqWNiSue0AAAA     at Socket.<anonymous> (/usr/lib/cncjs/app/index.js:16937:21)
2018-12-29T14:33:31.388Z - debug: service:cncengine socket.command("/dev/ttyUSB2", "gcode"): id=5OGKtp6cqWNiSue0AAAA     at Socket.<anonymous> (/usr/lib/cncjs/app/index.js:16937:21)
2018-12-29T14:33:31.389Z - debug: service:cncengine socket.command("/dev/ttyUSB2", "gcode"): id=5OGKtp6cqWNiSue0AAAA     at Socket.<anonymous> (/usr/lib/cncjs/app/index.js:16937:21)
2018-12-29T14:33:31.390Z - debug: service:cncengine socket.command("/dev/ttyUSB2", "gcode"): id=5OGKtp6cqWNiSue0AAAA     at Socket.<anonymous> (/usr/lib/cncjs/app/index.js:16937:21)
2018-12-29T14:33:33.539Z - debug: service:cncengine socket.command("/dev/ttyUSB2", "gcode"): id=5OGKtp6cqWNiSue0AAAA     at Socket.<anonymous> (/usr/lib/cncjs/app/index.js:16937:21)
2018-12-29T14:33:33.540Z - debug: service:cncengine socket.command("/dev/ttyUSB2", "gcode"): id=5OGKtp6cqWNiSue0AAAA     at Socket.<anonymous> (/usr/lib/cncjs/app/index.js:16937:21)
2018-12-29T14:33:33.541Z - debug: service:cncengine socket.command("/dev/ttyUSB2", "gcode"): id=5OGKtp6cqWNiSue0AAAA     at Socket.<anonymous> (/usr/lib/cncjs/app/index.js:16937:21)
2018-12-29T14:33:33.897Z - silly: controller:Marlin Reschedule temperture report query: now=1546094013897ms, timespan=10014ms
2018-12-29T14:33:34.068Z - debug: service:cncengine socket.command("/dev/ttyUSB2", "gcode"): id=5OGKtp6cqWNiSue0AAAA     at Socket.<anonymous> (/usr/lib/cncjs/app/index.js:16937:21)
2018-12-29T14:33:34.071Z - debug: service:cncengine socket.command("/dev/ttyUSB2", "gcode"): id=5OGKtp6cqWNiSue0AAAA     at Socket.<anonymous> (/usr/lib/cncjs/app/index.js:16937:21)
2018-12-29T14:33:34.072Z - debug: service:cncengine socket.command("/dev/ttyUSB2", "gcode"): id=5OGKtp6cqWNiSue0AAAA     at Socket.<anonymous> (/usr/lib/cncjs/app/index.js:16937:21)
2018-12-29T14:33:35.068Z - debug: service:cncengine socket.command("/dev/ttyUSB2", "gcode"): id=5OGKtp6cqWNiSue0AAAA     at Socket.<anonymous> (/usr/lib/cncjs/app/index.js:16937:21)
2018-12-29T14:33:35.070Z - debug: service:cncengine socket.command("/dev/ttyUSB2", "gcode"): id=5OGKtp6cqWNiSue0AAAA     at Socket.<anonymous> (/usr/lib/cncjs/app/index.js:16937:21)
2018-12-29T14:33:35.071Z - debug: service:cncengine socket.command("/dev/ttyUSB2", "gcode"): id=5OGKtp6cqWNiSue0AAAA     at Socket.<anonymous> (/usr/lib/cncjs/app/index.js:16937:21)
2018-12-29T14:33:35.645Z - debug: service:cncengine socket.command("/dev/ttyUSB2", "gcode"): id=5OGKtp6cqWNiSue0AAAA     at Socket.<anonymous> (/usr/lib/cncjs/app/index.js:16937:21)
2018-12-29T14:33:35.646Z - debug: service:cncengine socket.command("/dev/ttyUSB2", "gcode"): id=5OGKtp6cqWNiSue0AAAA     at Socket.<anonymous> (/usr/lib/cncjs/app/index.js:16937:21)
2018-12-29T14:33:35.647Z - debug: service:cncengine socket.command("/dev/ttyUSB2", "gcode"): id=5OGKtp6cqWNiSue0AAAA     at Socket.<anonymous> (/usr/lib/cncjs/app/index.js:16937:21)
2018-12-29T14:33:35.652Z - silly: controller:Marlin Reschedule current position query: now=1546094015652ms, timespan=5258ms
2018-12-29T14:33:35.982Z - silly: controller:Marlin < T:-15.00 /0.00 @:0
2018-12-29T14:33:35.982Z - silly: controller:Marlin controller.on('temperature'): source=server, line="M114", res={"ok":false,"extruder":{"deg":"-15.00","degTarget":"0.00","power":"0"},"heatedBed":{},"raw":"T:-15.00 /0.00 @:0"}
2018-12-29T14:33:39.000Z - silly: controller:Marlin <  T:-15.00 /0.00 @:0
2018-12-29T14:33:39.001Z - silly: controller:Marlin controller.on('temperature'): source=server, line="M114", res={"ok":false,"extruder":{"deg":"-15.00","degTarget":"0.00","power":"0"},"heatedBed":{},"raw":" T:-15.00 /0.00 @:0"}
2018-12-29T14:33:40.656Z - silly: controller:Marlin Reschedule current position query: now=1546094020656ms, timespan=5004ms

#### Versions

- CNCjs: 1.9.15
- Node.js: 11.3.0-1
- NPM: 6.4.1-2

#### How Do You Install CNCjs?

- [] NPM
- [ ] Download the CNCjs Desktop Application
- [x] Archlinux AUR

#### CNC Controller

- [] Grbl
- [] Marlin
- [ ] Smoothieware
- [ ] TinyG/g2core

#### Hardware

- [] Raspberry Pi
- [x ] Desktop or Laptop
- [ ] Mobile Device

#### Operating System

- [] Not Applicable
- [ ] Windows
- [ ] Mac
- [x ] Linux

**Comment by dudman** [comment]
I wish I knew what the problem was, but I started again from zero on a different linux computer, and got it working.
