### ISSUE TITLE
[INSTALLATION] [ERROR] [BUG] install not possible on desktop

### ISSUE THREAD

**Issue by NervenCid** [cncjs/cncjs#524]
#### Description

When i try to install cncjs i got these error:

C:\Users\nerve\AppData\Roaming\npm\node_modules\cncjs\node_modules\serialport>if not defined npm_config_node_gyp (node "C:\Program Files\nodejs\node_modules\npm\node_modules\npm-lifecycle\node-gyp-bin\\..\..\node_modules\node-gyp\bin\node-gyp.js" rebuild )  else (node "C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\bin\node-gyp.js" rebuild )
Los proyectos de esta solución se van a compilar de uno en uno. Para habilitar la compilación en paralelo, agregue el modificador "/m".
  serialport.cpp
  serialport_win.cpp
  win_delay_load_hook.cc
c:\users\nerve\appdata\roaming\npm\node_modules\cncjs\node_modules\serialport\src\serialport.cpp(41): error C2661: 'v8::Value::ToString': ninguna función sobrecargada
acepta 0 argumentos [C:\Users\nerve\AppData\Roaming\npm\node_modules\cncjs\node_modules\serialport\build\serialport.vcxproj]
c:\users\nerve\appdata\roaming\npm\node_modules\cncjs\node_modules\serialport\src\serialport.cpp(41): error C2512: 'v8::String::Utf8Value::Utf8Value': no hay disponibl
e un constructor predeterminado adecuado [C:\Users\nerve\AppData\Roaming\npm\node_modules\cncjs\node_modules\serialport\build\serialport.vcxproj]
c:\users\nerve\appdata\roaming\npm\node_modules\cncjs\node_modules\serialport\src\serialport.cpp(48): error C2661: 'v8::Value::ToObject': ninguna función sobrecargada
acepta 0 argumentos [C:\Users\nerve\AppData\Roaming\npm\node_modules\cncjs\node_modules\serialport\build\serialport.vcxproj]
c:\users\nerve\appdata\roaming\npm\node_modules\cncjs\node_modules\serialport\src\serialport.cpp(95): warning C4996: 'Nan::Callback::Call': se declaró desusado [C:\Use
rs\nerve\AppData\Roaming\npm\node_modules\cncjs\node_modules\serialport\build\serialport.vcxproj]
  c:\users\nerve\appdata\roaming\npm\node_modules\cncjs\node_modules\nan\nan.h(1740): note: vea la declaración de 'Nan::Callback::Call'
c:\users\nerve\appdata\roaming\npm\node_modules\cncjs\node_modules\serialport\src\serialport.cpp(113): error C2661: 'v8::Value::ToObject': ninguna función sobrecargada
 acepta 0 argumentos [C:\Users\nerve\AppData\Roaming\npm\node_modules\cncjs\node_modules\serialport\build\serialport.vcxproj]
c:\users\nerve\appdata\roaming\npm\node_modules\cncjs\node_modules\serialport\src\serialport.cpp(150): warning C4996: 'Nan::Callback::Call': se declaró desusado [C:\Us
ers\nerve\AppData\Roaming\npm\node_modules\cncjs\node_modules\serialport\build\serialport.vcxproj]
  c:\users\nerve\appdata\roaming\npm\node_modules\cncjs\node_modules\nan\nan.h(1740): note: vea la declaración de 'Nan::Callback::Call'
c:\users\nerve\appdata\roaming\npm\node_modules\cncjs\node_modules\serialport\src\serialport.cpp(188): warning C4996: 'Nan::Callback::Call': se declaró desusado [C:\Us
ers\nerve\AppData\Roaming\npm\node_modules\cncjs\node_modules\serialport\build\serialport.vcxproj]
  c:\users\nerve\appdata\roaming\npm\node_modules\cncjs\node_modules\nan\nan.h(1740): note: vea la declaración de 'Nan::Callback::Call'
c:\users\nerve\appdata\roaming\npm\node_modules\cncjs\node_modules\serialport\src\serialport.cpp(231): warning C4996: 'Nan::Callback::Call': se declaró desusado [C:\Us
ers\nerve\AppData\Roaming\npm\node_modules\cncjs\node_modules\serialport\build\serialport.vcxproj]
  c:\users\nerve\appdata\roaming\npm\node_modules\cncjs\node_modules\nan\nan.h(1740): note: vea la declaración de 'Nan::Callback::Call'
c:\users\nerve\appdata\roaming\npm\node_modules\cncjs\node_modules\serialport\src\serialport.cpp(250): error C2661: 'v8::Value::ToObject': ninguna función sobrecargada
 acepta 0 argumentos [C:\Users\nerve\AppData\Roaming\npm\node_modules\cncjs\node_modules\serialport\build\serialport.vcxproj]
c:\users\nerve\appdata\roaming\npm\node_modules\cncjs\node_modules\serialport\src\serialport.cpp(285): warning C4996: 'Nan::Callback::Call': se declaró desusado [C:\Us
ers\nerve\AppData\Roaming\npm\node_modules\cncjs\node_modules\serialport\build\serialport.vcxproj]
  c:\users\nerve\appdata\roaming\npm\node_modules\cncjs\node_modules\nan\nan.h(1740): note: vea la declaración de 'Nan::Callback::Call'
c:\users\nerve\appdata\roaming\npm\node_modules\cncjs\node_modules\serialport\src\serialport.cpp(329): warning C4996: 'v8::Object::Set': se declaró desusado [C:\Users\
nerve\AppData\Roaming\npm\node_modules\cncjs\node_modules\serialport\build\serialport.vcxproj]
  c:\users\nerve\appdata\local\node-gyp\cache\12.11.1\include\node\v8.h(3402): note: vea la declaración de 'v8::Object::Set'
c:\users\nerve\appdata\roaming\npm\node_modules\cncjs\node_modules\serialport\src\serialport.cpp(330): warning C4996: 'v8::Object::Set': se declaró desusado [C:\Users\
nerve\AppData\Roaming\npm\node_modules\cncjs\node_modules\serialport\build\serialport.vcxproj]
  c:\users\nerve\appdata\local\node-gyp\cache\12.11.1\include\node\v8.h(3402): note: vea la declaración de 'v8::Object::Set'
c:\users\nerve\appdata\roaming\npm\node_modules\cncjs\node_modules\serialport\src\serialport.cpp(331): warning C4996: 'v8::Object::Set': se declaró desusado [C:\Users\
nerve\AppData\Roaming\npm\node_modules\cncjs\node_modules\serialport\build\serialport.vcxproj]
  c:\users\nerve\appdata\local\node-gyp\cache\12.11.1\include\node\v8.h(3402): note: vea la declaración de 'v8::Object::Set'
c:\users\nerve\appdata\roaming\npm\node_modules\cncjs\node_modules\serialport\src\serialport.cpp(336): warning C4996: 'Nan::Callback::Call': se declaró desusado [C:\Us
ers\nerve\AppData\Roaming\npm\node_modules\cncjs\node_modules\serialport\build\serialport.vcxproj]
  c:\users\nerve\appdata\roaming\npm\node_modules\cncjs\node_modules\nan\nan.h(1740): note: vea la declaración de 'Nan::Callback::Call'
c:\users\nerve\appdata\roaming\npm\node_modules\cncjs\node_modules\serialport\src\serialport.cpp(378): warning C4996: 'v8::Object::Set': se declaró desusado [C:\Users\
nerve\AppData\Roaming\npm\node_modules\cncjs\node_modules\serialport\build\serialport.vcxproj]
  c:\users\nerve\appdata\local\node-gyp\cache\12.11.1\include\node\v8.h(3402): note: vea la declaración de 'v8::Object::Set'
c:\users\nerve\appdata\roaming\npm\node_modules\cncjs\node_modules\serialport\src\serialport.cpp(383): warning C4996: 'Nan::Callback::Call': se declaró desusado [C:\Us
ers\nerve\AppData\Roaming\npm\node_modules\cncjs\node_modules\serialport\build\serialport.vcxproj]
  c:\users\nerve\appdata\roaming\npm\node_modules\cncjs\node_modules\nan\nan.h(1740): note: vea la declaración de 'Nan::Callback::Call'
c:\users\nerve\appdata\roaming\npm\node_modules\cncjs\node_modules\serialport\src\serialport.cpp(424): warning C4996: 'Nan::Callback::Call': se declaró desusado [C:\Us
ers\nerve\AppData\Roaming\npm\node_modules\cncjs\node_modules\serialport\build\serialport.vcxproj]
  c:\users\nerve\appdata\roaming\npm\node_modules\cncjs\node_modules\nan\nan.h(1740): note: vea la declaración de 'Nan::Callback::Call'
c:\users\nerve\appdata\roaming\npm\node_modules\cncjs\node_modules\serialport\src\serialport.cpp(460): error C2039: 'Handle': no es un miembro de 'v8' [C:\Users\nerve\
AppData\Roaming\npm\node_modules\cncjs\node_modules\serialport\build\serialport.vcxproj]
  c:\users\nerve\appdata\local\node-gyp\cache\12.11.1\include\node\v8-platform.h(16): note: vea la declaración de 'v8'
c:\users\nerve\appdata\roaming\npm\node_modules\cncjs\node_modules\serialport\src\serialport.cpp(460): error C2065: 'Handle': identificador no declarado [C:\Users\nerv
e\AppData\Roaming\npm\node_modules\cncjs\node_modules\serialport\build\serialport.vcxproj]
c:\users\nerve\appdata\roaming\npm\node_modules\cncjs\node_modules\serialport\src\serialport.cpp(460): error C2275: 'v8::Object': uso no válido de este tipo como expre
sión [C:\Users\nerve\AppData\Roaming\npm\node_modules\cncjs\node_modules\serialport\build\serialport.vcxproj]
  c:\users\nerve\appdata\roaming\npm\node_modules\cncjs\node_modules\serialport\src\serialport.cpp(460): note: vea la declaración de 'v8::Object'
c:\users\nerve\appdata\roaming\npm\node_modules\cncjs\node_modules\serialport\src\serialport.cpp(460): error C2065: 'target': identificador no declarado [C:\Users\nerv
e\AppData\Roaming\npm\node_modules\cncjs\node_modules\serialport\build\serialport.vcxproj]
c:\users\nerve\appdata\roaming\npm\node_modules\cncjs\node_modules\serialport\src\serialport.cpp(460): error C2182: 'init': uso no válido del tipo 'void' [C:\Users\ner
ve\AppData\Roaming\npm\node_modules\cncjs\node_modules\serialport\build\serialport.vcxproj]
c:\users\nerve\appdata\roaming\npm\node_modules\cncjs\node_modules\serialport\src\serialport.cpp(460): error C2448: 'init': el inicializador de estilo de función parec
e ser una definición de función [C:\Users\nerve\AppData\Roaming\npm\node_modules\cncjs\node_modules\serialport\build\serialport.vcxproj]
c:\users\nerve\appdata\roaming\npm\node_modules\cncjs\node_modules\serialport\src\serialport.cpp(485): warning C4312: 'conversión de tipo': conversión de 'int' a 'node
::addon_register_func' de mayor tamaño [C:\Users\nerve\AppData\Roaming\npm\node_modules\cncjs\node_modules\serialport\build\serialport.vcxproj]
c:\users\nerve\appdata\roaming\npm\node_modules\cncjs\node_modules\serialport\src\serialport_win.cpp(188): warning C4311: 'conversión de tipo': truncamiento de puntero
 de 'HANDLE' a 'int' [C:\Users\nerve\AppData\Roaming\npm\node_modules\cncjs\node_modules\serialport\build\serialport.vcxproj]
c:\users\nerve\appdata\roaming\npm\node_modules\cncjs\node_modules\serialport\src\serialport_win.cpp(188): warning C4302: 'conversión de tipo': truncamiento de 'HANDLE
' a 'int' [C:\Users\nerve\AppData\Roaming\npm\node_modules\cncjs\node_modules\serialport\build\serialport.vcxproj]
c:\users\nerve\appdata\roaming\npm\node_modules\cncjs\node_modules\serialport\src\serialport_win.cpp(198): warning C4312: 'conversión de tipo': conversión de 'int' a '
HANDLE' de mayor tamaño [C:\Users\nerve\AppData\Roaming\npm\node_modules\cncjs\node_modules\serialport\build\serialport.vcxproj]
c:\users\nerve\appdata\roaming\npm\node_modules\cncjs\node_modules\serialport\src\serialport_win.cpp(205): warning C4312: 'conversión de tipo': conversión de 'int' a '
HANDLE' de mayor tamaño [C:\Users\nerve\AppData\Roaming\npm\node_modules\cncjs\node_modules\serialport\build\serialport.vcxproj]
c:\users\nerve\appdata\roaming\npm\node_modules\cncjs\node_modules\serialport\src\serialport_win.cpp(215): warning C4312: 'conversión de tipo': conversión de 'int' a '
HANDLE' de mayor tamaño [C:\Users\nerve\AppData\Roaming\npm\node_modules\cncjs\node_modules\serialport\build\serialport.vcxproj]
c:\users\nerve\appdata\roaming\npm\node_modules\cncjs\node_modules\serialport\src\serialport_win.cpp(217): warning C4312: 'conversión de tipo': conversión de 'int' a '
HANDLE' de mayor tamaño [C:\Users\nerve\AppData\Roaming\npm\node_modules\cncjs\node_modules\serialport\build\serialport.vcxproj]
c:\users\nerve\appdata\roaming\npm\node_modules\cncjs\node_modules\serialport\src\serialport_win.cpp(221): warning C4312: 'conversión de tipo': conversión de 'int' a '
HANDLE' de mayor tamaño [C:\Users\nerve\AppData\Roaming\npm\node_modules\cncjs\node_modules\serialport\build\serialport.vcxproj]
c:\users\nerve\appdata\roaming\npm\node_modules\cncjs\node_modules\serialport\src\serialport_win.cpp(223): warning C4312: 'conversión de tipo': conversión de 'int' a '
HANDLE' de mayor tamaño [C:\Users\nerve\AppData\Roaming\npm\node_modules\cncjs\node_modules\serialport\build\serialport.vcxproj]
c:\users\nerve\appdata\roaming\npm\node_modules\cncjs\node_modules\serialport\src\serialport_win.cpp(227): warning C4312: 'conversión de tipo': conversión de 'int' a '
HANDLE' de mayor tamaño [C:\Users\nerve\AppData\Roaming\npm\node_modules\cncjs\node_modules\serialport\build\serialport.vcxproj]
c:\users\nerve\appdata\roaming\npm\node_modules\cncjs\node_modules\serialport\src\serialport_win.cpp(229): warning C4312: 'conversión de tipo': conversión de 'int' a '
HANDLE' de mayor tamaño [C:\Users\nerve\AppData\Roaming\npm\node_modules\cncjs\node_modules\serialport\build\serialport.vcxproj]
c:\users\nerve\appdata\roaming\npm\node_modules\cncjs\node_modules\serialport\src\serialport_win.cpp(234): warning C4312: 'conversión de tipo': conversión de 'int' a '
HANDLE' de mayor tamaño [C:\Users\nerve\AppData\Roaming\npm\node_modules\cncjs\node_modules\serialport\build\serialport.vcxproj]
c:\users\nerve\appdata\roaming\npm\node_modules\cncjs\node_modules\serialport\src\serialport_win.cpp(246): warning C4312: 'conversión de tipo': conversión de 'int' a '
HANDLE' de mayor tamaño [C:\Users\nerve\AppData\Roaming\npm\node_modules\cncjs\node_modules\serialport\build\serialport.vcxproj]
c:\users\nerve\appdata\roaming\npm\node_modules\cncjs\node_modules\serialport\src\serialport_win.cpp(256): warning C4312: 'conversión de tipo': conversión de 'int' a '
HANDLE' de mayor tamaño [C:\Users\nerve\AppData\Roaming\npm\node_modules\cncjs\node_modules\serialport\build\serialport.vcxproj]
c:\users\nerve\appdata\roaming\npm\node_modules\cncjs\node_modules\serialport\src\serialport_win.cpp(273): warning C4312: 'conversión de tipo': conversión de 'int' a '
HANDLE' de mayor tamaño [C:\Users\nerve\AppData\Roaming\npm\node_modules\cncjs\node_modules\serialport\build\serialport.vcxproj]
c:\users\nerve\appdata\roaming\npm\node_modules\cncjs\node_modules\serialport\src\serialport_win.cpp(304): error C2661: 'v8::Value::ToObject': ninguna función sobrecar
gada acepta 0 argumentos [C:\Users\nerve\AppData\Roaming\npm\node_modules\cncjs\node_modules\serialport\build\serialport.vcxproj]
c:\users\nerve\appdata\roaming\npm\node_modules\cncjs\node_modules\serialport\src\serialport_win.cpp(334): warning C4312: 'conversión de tipo': conversión de 'int' a '
HANDLE' de mayor tamaño [C:\Users\nerve\AppData\Roaming\npm\node_modules\cncjs\node_modules\serialport\build\serialport.vcxproj]
c:\users\nerve\appdata\roaming\npm\node_modules\cncjs\node_modules\serialport\src\serialport_win.cpp(360): warning C4312: 'conversión de tipo': conversión de 'int' a '
HANDLE' de mayor tamaño [C:\Users\nerve\AppData\Roaming\npm\node_modules\cncjs\node_modules\serialport\build\serialport.vcxproj]
c:\users\nerve\appdata\roaming\npm\node_modules\cncjs\node_modules\serialport\src\serialport_win.cpp(390): warning C4996: 'Nan::Callback::Call': se declaró desusado [C
:\Users\nerve\AppData\Roaming\npm\node_modules\cncjs\node_modules\serialport\build\serialport.vcxproj]
  c:\users\nerve\appdata\roaming\npm\node_modules\cncjs\node_modules\nan\nan.h(1740): note: vea la declaración de 'Nan::Callback::Call'
c:\users\nerve\appdata\roaming\npm\node_modules\cncjs\node_modules\serialport\src\serialport_win.cpp(408): error C2661: 'v8::Value::ToObject': ninguna función sobrecar
gada acepta 0 argumentos [C:\Users\nerve\AppData\Roaming\npm\node_modules\cncjs\node_modules\serialport\build\serialport.vcxproj]
c:\users\nerve\appdata\roaming\npm\node_modules\cncjs\node_modules\serialport\src\serialport_win.cpp(463): warning C4312: 'conversión de tipo': conversión de 'int' a '
HANDLE' de mayor tamaño [C:\Users\nerve\AppData\Roaming\npm\node_modules\cncjs\node_modules\serialport\build\serialport.vcxproj]
c:\users\nerve\appdata\roaming\npm\node_modules\cncjs\node_modules\serialport\src\serialport_win.cpp(480): warning C4312: 'conversión de tipo': conversión de 'int' a '
HANDLE' de mayor tamaño [C:\Users\nerve\AppData\Roaming\npm\node_modules\cncjs\node_modules\serialport\build\serialport.vcxproj]
c:\users\nerve\appdata\roaming\npm\node_modules\cncjs\node_modules\serialport\src\serialport_win.cpp(493): warning C4312: 'conversión de tipo': conversión de 'int' a '
HANDLE' de mayor tamaño [C:\Users\nerve\AppData\Roaming\npm\node_modules\cncjs\node_modules\serialport\build\serialport.vcxproj]
c:\users\nerve\appdata\roaming\npm\node_modules\cncjs\node_modules\serialport\src\serialport_win.cpp(503): warning C4312: 'conversión de tipo': conversión de 'int' a '
HANDLE' de mayor tamaño [C:\Users\nerve\AppData\Roaming\npm\node_modules\cncjs\node_modules\serialport\build\serialport.vcxproj]
c:\users\nerve\appdata\roaming\npm\node_modules\cncjs\node_modules\serialport\src\serialport_win.cpp(531): warning C4312: 'conversión de tipo': conversión de 'int' a '
HANDLE' de mayor tamaño [C:\Users\nerve\AppData\Roaming\npm\node_modules\cncjs\node_modules\serialport\build\serialport.vcxproj]
c:\users\nerve\appdata\roaming\npm\node_modules\cncjs\node_modules\serialport\src\serialport_win.cpp(542): warning C4312: 'conversión de tipo': conversión de 'int' a '
HANDLE' de mayor tamaño [C:\Users\nerve\AppData\Roaming\npm\node_modules\cncjs\node_modules\serialport\build\serialport.vcxproj]
c:\users\nerve\appdata\roaming\npm\node_modules\cncjs\node_modules\serialport\src\serialport_win.cpp(574): warning C4996: 'Nan::Callback::Call': se declaró desusado [C
:\Users\nerve\AppData\Roaming\npm\node_modules\cncjs\node_modules\serialport\build\serialport.vcxproj]
  c:\users\nerve\appdata\roaming\npm\node_modules\cncjs\node_modules\nan\nan.h(1740): note: vea la declaración de 'Nan::Callback::Call'
c:\users\nerve\appdata\roaming\npm\node_modules\cncjs\node_modules\serialport\src\serialport_win.cpp(590): warning C4312: 'conversión de tipo': conversión de 'int' a '
HANDLE' de mayor tamaño [C:\Users\nerve\AppData\Roaming\npm\node_modules\cncjs\node_modules\serialport\build\serialport.vcxproj]
c:\users\nerve\appdata\roaming\npm\node_modules\cncjs\node_modules\serialport\src\serialport_win.cpp(592): warning C4312: 'conversión de tipo': conversión de 'int' a '
HANDLE' de mayor tamaño [C:\Users\nerve\AppData\Roaming\npm\node_modules\cncjs\node_modules\serialport\build\serialport.vcxproj]
c:\users\nerve\appdata\roaming\npm\node_modules\cncjs\node_modules\serialport\src\serialport_win.cpp(921): warning C4996: 'Nan::Callback::Call': se declaró desusado [C
:\Users\nerve\AppData\Roaming\npm\node_modules\cncjs\node_modules\serialport\build\serialport.vcxproj]
  c:\users\nerve\appdata\roaming\npm\node_modules\cncjs\node_modules\nan\nan.h(1740): note: vea la declaración de 'Nan::Callback::Call'
c:\users\nerve\appdata\roaming\npm\node_modules\cncjs\node_modules\serialport\src\serialport_win.cpp(935): warning C4312: 'conversión de tipo': conversión de 'int' a '
HANDLE' de mayor tamaño [C:\Users\nerve\AppData\Roaming\npm\node_modules\cncjs\node_modules\serialport\build\serialport.vcxproj]
c:\users\nerve\appdata\roaming\npm\node_modules\cncjs\node_modules\serialport\src\serialport_win.cpp(944): warning C4312: 'conversión de tipo': conversión de 'int' a '
HANDLE' de mayor tamaño [C:\Users\nerve\AppData\Roaming\npm\node_modules\cncjs\node_modules\serialport\build\serialport.vcxproj]
gyp ERR! build error
gyp ERR! stack Error: `C:\Program Files (x86)\Microsoft Visual Studio\2017\BuildTools\MSBuild\15.0\Bin\MSBuild.exe` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onExit (C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\lib\build.js:196:23)
gyp ERR! stack     at ChildProcess.emit (events.js:210:5)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:272:12)
gyp ERR! System Windows_NT 10.0.17134
gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild"
gyp ERR! cwd C:\Users\nerve\AppData\Roaming\npm\node_modules\cncjs\node_modules\serialport
gyp ERR! node -v v12.11.1
gyp ERR! node-gyp -v v5.0.3
gyp ERR! not ok

#### Versions

- CNCjs: 1.9.x
- Node.js: 12.11.1
- NPM: 5.x

#### How Do You Install CNCjs?

- [x] NPM
- [ ] Download the CNCjs Desktop Application

#### CNC Controller

- [x] Grbl
- [ ] Smoothieware
- [ ] TinyG/g2core

#### Hardware

- [ ] Raspberry Pi
- [x] Desktop or Laptop
- [ ] Mobile Device

#### Operating System

- [ ] Not Applicable
- [x] Windows
- [ ] Mac
- [ ] Linux

**Comment by cheton** [comment]
@NervenCid 

The node-serialport 6.2.2 is only compatible with Node.js 10 and earlier versions.
See https://github.com/serialport/node-serialport/tree/v6.2.2#platform-support for details:

| Platform / Arch | Node v4.x | Node v6.x | Node v8.x | Node v9.x | Node v10.x |
|       ---       | --- | --- | --- | --- | --- |
| Linux / ia32⁴   |  ☑  |  ☑  |  ☑  |  ☑  |  ☐  |
| Linux / x64     |  ☑  |  ☑  |  ☑  |  ☑  |  ☑  |
| Linux / ARM v6¹ |  ☐  |  ☐  |  ☐  |  ☐  |  ☐  |
| Linux / ARM v7¹ |  ☐  |  ☐  |  ☐  |  ☐  |  ☐  |
| Linux / ARM v8¹ |  ☐  |  ☐  |  ☐  |  ☐  |  ☐  |
| Linux / MIPSel¹ |  ☐  |  ☐  |  ☐  |  ☐  |  ☐  |
| Linux / PPC64¹  |  ☐  |  ☐  |  ☐  |  ☐  |  ☐  |
| Windows² / x86  |  ☐  |  ☑  |  ☑  |  ☑  |  ☑  |
| Windows² / x64  |  ☑  |  ☑  |  ☑  |  ☑  |  ☑  |
| OSX³ / x64      |  ☑  |  ☑  |  ☑  |  ☑  |  ☑  |


You can try downgrading Node.js from 12 to 10 (or 8) to resolve this issue.
