### ISSUE TITLE
Latest Docker Image Cannot Locate Bindings

### ISSUE THREAD

**Issue by InfernoCV** [cncjs/cncjs#625]
#### Description

On a fresh install of Ubuntu 20.04 I am unable to run cncjs with Docker following the commands within the Wiki. In the container log I have the following error:

```
Error: { Error: Could not locate the bindings file. Tried:
 → /dist/cncjs/node_modules/@serialport/bindings/build/bindings.node
 → /dist/cncjs/node_modules/@serialport/bindings/build/Debug/bindings.node
 → /dist/cncjs/node_modules/@serialport/bindings/build/Release/bindings.node
 → /dist/cncjs/node_modules/@serialport/bindings/out/Debug/bindings.node
 → /dist/cncjs/node_modules/@serialport/bindings/Debug/bindings.node
 → /dist/cncjs/node_modules/@serialport/bindings/out/Release/bindings.node
 → /dist/cncjs/node_modules/@serialport/bindings/Release/bindings.node
 → /dist/cncjs/node_modules/@serialport/bindings/build/default/bindings.node
 → /dist/cncjs/node_modules/@serialport/bindings/compiled/10.21.0/linux/x64/bindings.node
 → /dist/cncjs/node_modules/@serialport/bindings/addon-build/release/install-root/bindings.node
 → /dist/cncjs/node_modules/@serialport/bindings/addon-build/debug/install-root/bindings.node
 → /dist/cncjs/node_modules/@serialport/bindings/addon-build/default/install-root/bindings.node
 → /dist/cncjs/node_modules/@serialport/bindings/lib/binding/node-v64-linux-x64/bindings.node
    at bindings (/dist/cncjs/node_modules/bindings/bindings.js:126:9)
    at Object.<anonymous> (/dist/cncjs/node_modules/@serialport/bindings/lib/linux.js:1:36)
    at Module._compile (internal/modules/cjs/loader.js:778:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
    at Module.require (internal/modules/cjs/loader.js:692:17)
    at require (internal/modules/cjs/helpers.js:25:18)
    at Object.<anonymous> (/dist/cncjs/node_modules/@serialport/bindings/lib/index.js:14:22)
    at Module._compile (internal/modules/cjs/loader.js:778:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
    at Module.require (internal/modules/cjs/loader.js:692:17)
  tries:
   [ '/dist/cncjs/node_modules/@serialport/bindings/build/bindings.node',
     '/dist/cncjs/node_modules/@serialport/bindings/build/Debug/bindings.node',
     '/dist/cncjs/node_modules/@serialport/bindings/build/Release/bindings.node',
     '/dist/cncjs/node_modules/@serialport/bindings/out/Debug/bindings.node',
     '/dist/cncjs/node_modules/@serialport/bindings/Debug/bindings.node',
     '/dist/cncjs/node_modules/@serialport/bindings/out/Release/bindings.node',
     '/dist/cncjs/node_modules/@serialport/bindings/Release/bindings.node',
     '/dist/cncjs/node_modules/@serialport/bindings/build/default/bindings.node',
     '/dist/cncjs/node_modules/@serialport/bindings/compiled/10.21.0/linux/x64/bindings.node',
     '/dist/cncjs/node_modules/@serialport/bindings/addon-build/release/install-root/bindings.node',
     '/dist/cncjs/node_modules/@serialport/bindings/addon-build/debug/install-root/bindings.node',
     '/dist/cncjs/node_modules/@serialport/bindings/addon-build/default/install-root/bindings.node',
     '/dist/cncjs/node_modules/@serialport/bindings/lib/binding/node-v64-linux-x64/bindings.node' ] }
```

#### Versions

Using Latest tag for Docker image
[https://hub.docker.com/layers/cncjs/cncjs/latest/images/sha256-b25f8dbf75a863692dd80c46bc00689f052457177977ee4da99b1899728bc36b?context=explore](https://hub.docker.com/layers/cncjs/cncjs/latest/images/sha256-b25f8dbf75a863692dd80c46bc00689f052457177977ee4da99b1899728bc36b?context=explore)

#### How Do You Install CNCjs?

Docker
```
Client:
 Version:           19.03.8
 API version:       1.40
 Go version:        go1.13.8
 Git commit:        afacb8b7f0
 Built:             Tue Jun 23 22:26:12 2020
 OS/Arch:           linux/amd64
 Experimental:      false
```

#### Hardware

Intel Celeron J3455 NUC (4-core, 16GB RAM)

#### Operating System

Ubuntu 20.04 Server

**Comment by labajo** [comment]
Hi, I did the following to have cncjs running on a OMV5 (Debian) with Docker.
I created the file **.dockerignore** in the root level of the project with this content:
```
node_modules
```
I think that this is your main issue, because this forces to install the node_modules using the docker environment and not reuse your host node_modules.

I also try two other changes:

- I updated in the Dockerfile the node version to **12**
- In order to avoid problems with udevadm spawn call I add the following line in the Dockerfile after the MAINTAINER line:
```
RUN apt update &&  apt install -y udev socat
```

Now you can create your own image using the following command:

```sh
docker build --pull --rm -f "Dockerfile" -t cncjs:1.9.22 "." 
```
and run later the container using this

```sh
docker run -d --device /dev/ttyACM0:/dev/ttyACM0 -p 5003:8000 --name cncjs cncjs:1.9.22
```

I hope this solve your problem and perhaps could help @cheton
