### ISSUE TITLE
API Information/Issue

### ISSUE THREAD

**Issue by ToxicDeathX** [cncjs/cncjs#663]
#### Description

Unable to get any access to the API system within CNCJS using the URL http://192.168.1.xxx/api/signin.

It keeps on saying either 401 or 403 depending on what API try to query and the users are assigned within the **settings->user-accounts**, without a user defined i can access the /api/signin but can't do anything further-more is there proper documentation on the API system and or how does one go about getting access to https://github.com/cncjs/cncjs/wiki/Server-API#authorized-access-only-endpoints.

I have tried using the following strings in a post request to the CNCJS server:

`{"enabled":true,"token":"token-was-here","name":"user-was-here"} `

**and**

`{
  enabled: true,
  token: <JWT>,
  name, <name>
}
`
the tool i used was RESTClient on firefox.

`
2020-11-29T18:57:16.191Z - warn app { JsonWebTokenError: jwt must be provided
    at Object.module.exports [as verify] (/usr/local/lib/node_modules/cncjs/node_modules/jsonwebtoken/verify.js:53:17)
    at _callee2$ (/usr/local/lib/node_modules/cncjs/dist/cncjs/server/index.js:4273:77)
    at tryCatch (/usr/local/lib/node_modules/cncjs/node_modules/regenerator-runtime/runtime.js:63:40)
    at Generator.invoke [as _invoke] (/usr/local/lib/node_modules/cncjs/node_modules/regenerator-runtime/runtime.js:293:22)
    at Generator.next (/usr/local/lib/node_modules/cncjs/node_modules/regenerator-runtime/runtime.js:118:21)
    at asyncGeneratorStep (/usr/local/lib/node_modules/cncjs/dist/cncjs/server/index.js:4022:103)
    at _next (/usr/local/lib/node_modules/cncjs/dist/cncjs/server/index.js:4024:194)
    at /usr/local/lib/node_modules/cncjs/dist/cncjs/server/index.js:4024:364
    at new Promise (<anonymous>)
    at /usr/local/lib/node_modules/cncjs/dist/cncjs/server/index.js:4024:97
    at /usr/local/lib/node_modules/cncjs/dist/cncjs/server/index.js:4310:22
    at Layer.handle_error (/usr/local/lib/node_modules/cncjs/node_modules/express/lib/router/layer.js:71:5)
    at trim_prefix (/usr/local/lib/node_modules/cncjs/node_modules/express/lib/router/index.js:315:13)
    at /usr/local/lib/node_modules/cncjs/node_modules/express/lib/router/index.js:284:7
    at Function.process_params (/usr/local/lib/node_modules/cncjs/node_modules/express/lib/router/index.js:335:12)
    at next (/usr/local/lib/node_modules/cncjs/node_modules/express/lib/router/index.js:275:10) name: 'JsonWebTokenError', message: 'jwt must be provided' }
2020-11-29T18:57:16.202Z - warn app Forbidden: ipaddr=192.168.1.xxx, code="credentials_required", message="No authorization token was found"
`

#### Versions

- CNCjs: 1.9.22
- Node.js: V10.21.0
- NPM: 6.14.9

#### How Do You Install CNCjs?

- [x] NPM
- [ ] Download the CNCjs Desktop Application

#### CNC Controller

- [x] Grbl
- [ ] Smoothieware
- [ ] TinyG/g2core

#### Hardware

- [x] Raspberry Pi
- [ ] Desktop or Laptop
- [ ] Mobile Device

#### Operating System

- [ ] Not Applicable
- [ ] Windows
- [ ] Mac
- [x] Linux

**Comment by PetyC** [comment]
> Ended up resolving my own issue with some more digging into the code but here is the flow that will need to be followed but might be incorrect but work.
> 
> Steps
> 
> 1: Post to :8000/api/signin with the body containing and in form method: { token="", name="USERNAME HERE", password="PASSWORD HERE" }
> 
> retrieve the token from the json output
> 
> 2: GET on IP:8000/api/controllers to get the data dump
> 
> 3: Filter the data

What parameters should I bring when sending a GET request in the third step? I tried many times but couldn't get the information, thanks for your help！
